---
- job:
    name: jjb-tox-cross-jenkins-job-builder
    description: Tests compatibility with master branch of jenkins-job-builder
    parent: tox-py27
    required-projects:
      - jjb/python-jenkins
      - jjb/jenkins-job-builder
    voting: true

- project:
    templates:
      - build-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-py27
        - openstack-tox-pypy:
            nodeset: ubuntu-bionic
        - jjb-tox-cross-jenkins-job-builder
    gate:
      jobs:
        - openstack-tox-linters
        - openstack-tox-py27
        - jjb-tox-cross-jenkins-job-builder
